package com.myspace.approval_system;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Request implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Leave Purpose")
	private java.lang.String purpose;

	@org.kie.api.definition.type.Label(value = "Leave Days")
	private java.lang.Integer days;

	public Request() {
	}

	public String toString() {
		return "Request{" + "purpose='" + purpose + '\'' + ", days='"
				+ days + '}';
	}

	public java.lang.String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(java.lang.String purpose) {
		this.purpose = purpose;
	}

	public java.lang.Integer getDays() {
		return this.days;
	}

	public void setDays(java.lang.Integer days) {
		this.days = days;
	}

	public Request(java.lang.String purpose, java.lang.Integer days) {
		this.purpose = purpose;
		this.days = days;
	}

}